name: traefik

include:
  - compose/edge/docker-compose.yaml
  - compose/tailscale/docker-compose.yaml
  - compose/observability/docker-compose.yaml

networks:
  proxy:
    name: traefik_proxy
    driver: bridge
  tailscale:
    name: tailscale_services
    driver: bridge
    ipam:
      config:
        - subnet: ${TS_SERVICE_SUBNET:?}
