import { chmod, open, readFile, rename, stat, unlink, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

export function redactSecret(secret?: string): string {
  if (!secret) return "";
  if (secret.length <= 8) return "********";
  return `${secret.slice(0, 4)}...${secret.slice(-4)}`;
}

export function parseEnv(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let val = trimmed.slice(eqIdx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    result[key] = val;
  }
  return result;
}

export const LEGACY_KEYS_TO_SCRUB = [
  "TS_API_TOKEN",
  "TS_AUTHKEY",
  "DOCKER_POOL",
  "TS_SERVICE_SUBNET",
  "DIRECT_DOMAIN",
] as const;

export function updateEnvContent(
  originalContent: string,
  updates: Record<string, string>,
  scrubKeys: string[] = [...LEGACY_KEYS_TO_SCRUB],
): string {
  const remaining = new Map(Object.entries(updates));
  // The root .env is configuration, not credential storage. The router auth
  // key belongs only in the dedicated, ignored env/.env.tailscale.local file.
  remaining.delete("TS_API_TOKEN");
  remaining.delete("TS_AUTHKEY");

  const scrubSet = new Set(scrubKeys);

  const lines = originalContent ? originalContent.split(/\r?\n/) : [];
  const updatedLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trimStart();
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=/.exec(trimmed);
    const key = match?.[1];
    if (!key) {
      updatedLines.push(line);
      continue;
    }
    if (key === "TS_API_TOKEN" || key === "TS_AUTHKEY") {
      continue;
    }
    if (remaining.has(key)) {
      const newVal = remaining.get(key)!;
      remaining.delete(key);
      updatedLines.push(`${key}=${JSON.stringify(newVal)}`);
    } else if (scrubSet.has(key)) {
      // Scrub stale/deprecated legacy keys so they do not persist into Compose
      continue;
    } else {
      updatedLines.push(line);
    }
  }

  if (remaining.size > 0) {
    if (updatedLines.length > 0 && updatedLines[updatedLines.length - 1] !== "") {
      updatedLines.push("");
    }
    for (const [key, val] of remaining.entries()) {
      updatedLines.push(`${key}=${JSON.stringify(val)}`);
    }
  }

  const result = updatedLines.join("\n");
  return result.endsWith("\n") ? result : `${result}\n`;
}

export function updateTailscaleSecretContent(
  originalContent: string,
  authKey: string,
  expiresAt: string,
): string {
  const retained = originalContent
    .split(/\r?\n/)
    .filter((line) => {
      const key = /^\s*([A-Za-z_][A-Za-z0-9_]*)=/.exec(line)?.[1];
      return key !== "TS_API_TOKEN" && key !== "TS_AUTHKEY" && key !== "TS_AUTHKEY_EXPIRES_AT";
    });

  while (retained.length > 0 && retained[retained.length - 1] === "") retained.pop();
  if (retained.length > 0) retained.push("");
  retained.push(
    "# Generated by scripts/onboarding.ts. Keep this file private and gitignored.",
    `# Renew before ${expiresAt} with: TS_API_TOKEN=\"...\" bun scripts/onboarding.ts --rotate-authkey`,
    `TS_AUTHKEY=${JSON.stringify(authKey)}`,
    `TS_AUTHKEY_EXPIRES_AT=${JSON.stringify(expiresAt)}`,
  );
  return `${retained.join("\n")}\n`;
}

export async function writeTailscaleSecretFile(
  filePath: string,
  authKey: string,
  expiresAt: string,
): Promise<void> {
  let original = "";
  if (existsSync(filePath)) original = await readFile(filePath, "utf-8");
  const content = updateTailscaleSecretContent(original, authKey, expiresAt);
  const temporaryPath = `${filePath}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  let handle: Awaited<ReturnType<typeof open>> | undefined;
  try {
    handle = await open(temporaryPath, "wx", 0o600);
    await handle.writeFile(content, "utf-8");
    await handle.sync();
    await handle.close();
    handle = undefined;
    await rename(temporaryPath, filePath);
    await chmod(filePath, 0o600);
    const finalStat = await stat(filePath);
    if ((finalStat.mode & 0o777) !== 0o600) {
      throw new Error(`Failed to secure Tailscale credential file '${filePath}' with mode 0600`);
    }
  } finally {
    await handle?.close().catch(() => {});
    await unlink(temporaryPath).catch(() => {});
  }
}

export async function mergeEnvFile(
  filePath: string,
  updates: Record<string, string>,
): Promise<void> {
  let original = "";
  if (existsSync(filePath)) {
    original = await readFile(filePath, "utf-8");
  }
  const merged = updateEnvContent(original, updates);
  await writeFile(filePath, merged, { mode: 0o600 });
  await chmod(filePath, 0o600).catch(() => {});
}

/** Scrubs credentials and stale keys from an explicitly selected legacy env file. */
export async function scrubLegacyEnvFile(
  filePath: string,
  extraKeysToScrub: string[] = ["TS_ROUTES"],
): Promise<{ scrubbed: boolean; removedKeys: string[] }> {
  if (!existsSync(filePath)) {
    return { scrubbed: false, removedKeys: [] };
  }

  const original = await readFile(filePath, "utf-8");
  const scrubTargetSet = new Set([...LEGACY_KEYS_TO_SCRUB, ...extraKeysToScrub]);
  const lines = original.split(/\r?\n/);
  const remainingLines: string[] = [];
  const removedKeys: string[] = [];

  for (const line of lines) {
    const trimmed = line.trimStart();
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=/.exec(trimmed);
    const key = match?.[1];
    if (key && scrubTargetSet.has(key)) {
      removedKeys.push(key);
      continue;
    }
    remainingLines.push(line);
  }

  if (removedKeys.length > 0) {
    const newContent = remainingLines.join("\n");
    await writeFile(filePath, newContent.endsWith("\n") ? newContent : `${newContent}\n`, { mode: 0o600 });
    await chmod(filePath, 0o600).catch(() => {});
    return { scrubbed: true, removedKeys };
  }

  return { scrubbed: false, removedKeys: [] };
}
